### ISSUE TITLE
EPIC: Categories

### ISSUE THREAD

**Issue by claudio-cruz** [claudio-cruz/DevBooks#5]
**Categories:**

- [x] Top recommended books
- [x] Comments
- [x] Likes
- [ ] Add to favorites
- [ ] Five start rating
- [x] Buy button
- [x] Approve comments
- [x] Manage books
